package com.questland.handbook.flatbuffers;// automatically generated by the FlatBuffers compiler, do not modify

public final class BannerPart {
  private BannerPart() { }
  public static final byte Unknown = 0;
  public static final byte Shape = 1;
  public static final byte ShapeColor1 = 2;
  public static final byte ShapeColor2 = 3;
  public static final byte Crown = 4;
  public static final byte Symbol = 5;
  public static final byte SymbolColor = 6;

  public static final String[] names = { "Unknown", "Shape", "ShapeColor1", "ShapeColor2", "Crown", "Symbol", "SymbolColor", };

  public static String name(int e) { return names[e]; }
}

