package com.questland.handbook.flatbuffers;// automatically generated by the FlatBuffers compiler, do not modify

public final class EquipSlot {
  private EquipSlot() { }
  public static final byte Unknown = 0;
  public static final byte Head = 1;
  public static final byte Chest = 2;
  public static final byte Hands = 3;
  public static final byte Legs = 4;
  public static final byte Ring = 5;
  public static final byte Amulet = 6;
  public static final byte MainHand = 7;
  public static final byte OffHand = 8;
  public static final byte Pet = 9;
  public static final byte Talisman = 10;
  public static final byte Potion = 11;
  public static final byte Orb = 12;
  public static final byte Lockbox = 13;
  public static final byte Usable = 14;
  public static final byte Valuable = 15;
  public static final byte Giftbox = 16;
  public static final byte ExactShard = 17;
  public static final byte BarberShop = 18;
  public static final byte GuildBanner = 19;
  public static final byte TalentOne = 20;
  public static final byte TalentTwo = 21;
  public static final byte TalentThree = 22;

  public static final String[] names = { "Unknown", "Head", "Chest", "Hands", "Legs", "Ring", "Amulet", "MainHand", "OffHand", "Pet", "Talisman", "Potion", "Orb", "Lockbox", "Usable", "Valuable", "Giftbox", "ExactShard", "BarberShop", "GuildBanner", "TalentOne", "TalentTwo", "TalentThree", };

  public static String name(int e) { return names[e]; }
}

