package com.questland.handbook.flatbuffers;// automatically generated by the FlatBuffers compiler, do not modify

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class ItemTemplates extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static ItemTemplates getRootAsItemTemplates(ByteBuffer _bb) { return getRootAsItemTemplates(_bb, new ItemTemplates()); }
  public static ItemTemplates getRootAsItemTemplates(ByteBuffer _bb, ItemTemplates obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public ItemTemplates __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ItemTemplate templates(int j) { return templates(new ItemTemplate(), j); }
  public ItemTemplate templates(ItemTemplate obj, int j) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int templatesLength() { int o = __offset(4); return o != 0 ? __vector_len(o) : 0; }
  public ItemTemplate.Vector templatesVector() { return templatesVector(new ItemTemplate.Vector()); }
  public ItemTemplate.Vector templatesVector(ItemTemplate.Vector obj) { int o = __offset(4); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createItemTemplates(FlatBufferBuilder builder,
      int templatesOffset) {
    builder.startTable(1);
    ItemTemplates.addTemplates(builder, templatesOffset);
    return ItemTemplates.endItemTemplates(builder);
  }

  public static void startItemTemplates(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addTemplates(FlatBufferBuilder builder, int templatesOffset) { builder.addOffset(0, templatesOffset, 0); }
  public static int createTemplatesVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startTemplatesVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endItemTemplates(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public ItemTemplates get(int j) { return get(new ItemTemplates(), j); }
    public ItemTemplates get(ItemTemplates obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

