package com.questland.handbook.flatbuffers;// automatically generated by the FlatBuffers compiler, do not modify

public final class ItemGroup {
  private ItemGroup() { }
  public static final byte Unknown = 0;
  public static final byte Wearable = 1;
  public static final byte Orb = 2;
  public static final byte Part = 3;
  public static final byte Usable = 4;
  public static final byte UsableGiftboxLockbox = 5;

  public static final String[] names = { "Unknown", "Wearable", "Orb", "Part", "Usable", "UsableGiftboxLockbox", };

  public static String name(int e) { return names[e]; }
}

