package com.questland.handbook.flatbuffers;// automatically generated by the FlatBuffers compiler, do not modify

public final class ItemQuality {
  private ItemQuality() { }
  public static final byte Unknown = 0;
  public static final byte Common = 1;
  public static final byte Uncommon = 2;
  public static final byte Rare = 3;
  public static final byte Epic = 4;
  public static final byte Legendary = 5;
  public static final byte LegendaryPlus = 6;
  public static final byte Artifact = 7;
  public static final byte ArtifactPlus = 8;
  public static final byte Relic = 9;
  public static final byte RelicPlus = 10;

  public static final String[] names = { "Unknown", "Common", "Uncommon", "Rare", "Epic", "Legendary", "LegendaryPlus", "Artifact", "ArtifactPlus", "Relic", "RelicPlus", };

  public static String name(int e) { return names[e]; }
}

