package com.questland.handbook.flatbuffers;// automatically generated by the FlatBuffers compiler, do not modify

public final class ItemEffect {
  private ItemEffect() { }
  public static final byte Unknown = 0;
  public static final byte BronzeChestKey = 1;
  public static final byte SilverChestKey = 2;
  public static final byte GoldenChestKey = 3;
  public static final byte TrainingPill = 4;
  public static final byte MeditationCandle = 5;
  public static final byte SpinToken = 6;
  public static final byte ExtractPowder = 7;
  public static final byte Identify = 8;
  public static final byte AddEnergy = 9;
  public static final byte LockBoxKey = 10;
  public static final byte BronzeChestKeyPart = 11;
  public static final byte SilverChestKeyPart = 12;
  public static final byte GoldenChestKeyPart = 13;
  public static final byte ShardWeapon = 14;
  public static final byte ShardArmor = 15;
  public static final byte ShardTrinket = 16;
  public static final byte BankPoint = 17;
  public static final byte RenewTokenLesser = 18;
  public static final byte RenewTokenSuperior = 19;
  public static final byte Material = 20;
  public static final byte CollectionSeal = 21;
  public static final byte ItemExperience = 22;
  public static final byte BarterShopCurrency = 23;
  public static final byte AddStamina = 24;
  public static final byte LeagueFight = 25;
  public static final byte ReforgeCurrency = 26;
  public static final byte OrbEnhanceHealth = 27;
  public static final byte OrbEnhanceDamage = 28;
  public static final byte OrbEnhanceDefence = 29;
  public static final byte BattleEventBoss = 30;
  public static final byte BattleEvent = 31;
  public static final byte BattleEventLocations = 32;
  public static final byte BattleEventRanking = 33;
  public static final byte BattleEventShop = 34;
  public static final byte GuildCurrency = 35;
  public static final byte BattleEventMultiplierToken = 36;
  public static final byte VanityItem = 37;
  public static final byte BattleX10 = 38;
  public static final byte TalentSeed = 39;
  public static final byte SkipBattleEventBoss = 40;
  public static final byte IncreaseNameChanges = 41;
  public static final byte BattleArenaGo = 42;

  public static final String[] names = { "Unknown", "BronzeChestKey", "SilverChestKey", "GoldenChestKey", "TrainingPill", "MeditationCandle", "SpinToken", "ExtractPowder", "Identify", "AddEnergy", "LockBoxKey", "BronzeChestKeyPart", "SilverChestKeyPart", "GoldenChestKeyPart", "ShardWeapon", "ShardArmor", "ShardTrinket", "BankPoint", "RenewTokenLesser", "RenewTokenSuperior", "Material", "CollectionSeal", "ItemExperience", "BarterShopCurrency", "AddStamina", "LeagueFight", "ReforgeCurrency", "OrbEnhanceHealth", "OrbEnhanceDamage", "OrbEnhanceDefence", "BattleEventBoss", "BattleEvent", "BattleEventLocations", "BattleEventRanking", "BattleEventShop", "GuildCurrency", "BattleEventMultiplierToken", "VanityItem", "BattleX10", "TalentSeed", "SkipBattleEventBoss", "IncreaseNameChanges", "BattleArenaGo", };

  public static String name(int e) { return names[e]; }
}

