package com.questland.handbook.flatbuffers;// automatically generated by the FlatBuffers compiler, do not modify

public final class StatType {
  private StatType() { }
  public static final byte Unknown = 0;
  public static final byte Attack = 1;
  public static final byte Defence = 2;
  public static final byte Health = 3;
  public static final byte Magic = 4;

  public static final String[] names = { "Unknown", "Attack", "Defence", "Health", "Magic", };

  public static String name(int e) { return names[e]; }
}

