package com.questland.handbook.flatbuffers;// automatically generated by the FlatBuffers compiler, do not modify

public final class TargetPlace {
  private TargetPlace() { }
  public static final byte None = 0;
  public static final byte CityCraft = 1;
  public static final byte EventCraft = 2;
  public static final byte GuildShop = 3;
  public static final byte GuildResearch = 4;

  public static final String[] names = { "None", "CityCraft", "EventCraft", "GuildShop", "GuildResearch", };

  public static String name(int e) { return names[e]; }
}

